# Site settings
title: Rendering Invisibility Project Diary
email: krf@aber.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  This is a blog created to track progress within my Major Project at Aberystwyth
  University. My project title is Rendering Invisibility and I am looking into
  how an invisibility cloak can be modelled using modern theories about practical
  invisibility cloaks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://krf12.github.io/RenderingInvisibility" # the base hostname & protocol for your site
twitter_username: HugCushionKit
github_username:  krf12

# Build settings
markdown: kramdown
