# Site settings
title: Rendering Invisibility Project Diary
email: krf@aber.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  This is where I will keep track of the progress of my Major Project for my
  Undergraduate Course. My project is about using WebGL to render a realistic
  invisibility cloak using recent research.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://krf12.github.io/Renderinginvisibility" # the base hostname & protocol for your site
twitter_username: HugCushionKit
github_username:  krf12

# Build settings
markdown: kramdown
